### ISSUE TITLE
Can this method work with Akka 2.4 and Spring Boot without XML ?

### ISSUE THREAD

**Issue by javajack** [sabomichal/akka-java-springfactory#1]
Can this method work with Akka 2.4 and Spring Boot without XML ?

**Comment by sabomichal** [comment]
This method is mainly intended to work with Spring XML configuration. When using Spring Boot, you wouldn't need the factories since you can configure ActorSystem and actors itself programmatically.

**Comment by sabomichal** [comment]
And yes, it works with Akka 2.4 with the necessary changes in the dependency list and compiling against Java 8.

**Comment by javajack** [comment]
I would be glad to explore a sample of Spring Boot that doesn't use XML ( and possibly your code ) and still makes spring defined beans' injection possible in Akka Actors.

I just published a repo to share the way I am leveraging your code in Spring Boot with Annotations. Where I am able to inject Spring services / beans into Actor annotated with @Actor.

https://github.com/javajack/spring-boot-1.3-akka-2.3.14

Could I get away with your code ? Or is there a better way to do it in Spring Boot ?

**Comment by sabomichal** [comment]
I'll try to take a look, however I am a bit busy these days, so I can not guarantee it.

**Comment by sabomichal** [comment]
I was just looking at your code and I see it is working fine, also the DI. What exactly do you want to do?

**Comment by sabomichal** [comment]
I think you should stick with these examples when using spring boot: https://github.com/typesafehub/activator-akka-java-spring

**Comment by javajack** [comment]
Alright. Thanks for the feedback :)
